env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=${TRAVIS_REPO_SLUG}
  - secure: pJaVDsmIXqw2mvvdE6cphWHkwR2yhzVSTxWECYSOUELS77aPeqw8HLEWNom+ajVGR82OZG5scNINiojJPSBNx9AzQ1APH2HeWmtEc0q+fuevtMYV9guVXiFurmApT9pgrxDvpHcNJ7Ke6CJlJcYmMQJlY3wElL/SM1rvhsbFCcXkIpl2FtRNAb9OxHnDEIJgSOM5XJwD0KP/7opkoSqJTXyBMX0If9GuUydP+mH5V9uWzL1QuVNFA7CV9xPpBKYlAcFxHSSHl2aB++6pkglXN9U4W8j6BkvRGFJG6Ede2W1Beb32RlaPDWHhfFI0E6tNPEXxtYE12QSYZkEDpmS+DNBqXtM/jjiclY/HyP4UAs5TOoiYy0BuVQlWc5uRKOBZlBn5iRXeg8CGcQ9VY4HGba8T2aS8kEZ3LkCuSCrmB5/mQIgXBmgjOnZFCwSHfHnkE4sNEr/eMvb7DDyXHfQEWRKrXuLESQFPJIRH8Oh2bzaUonqZ/5P+KQXqFolp4Vge5/P5eNOLZvNckYImjFBfUEvZHSHpPzYrk2h+wcS9t9bl91w3G0ycQmLLFTx6C5IsJI4+nbXxz1mudRl7FnvBPyeMngB5uOMcNpy05AGydp5qk8x6LBR8EKSOK5yCCYTo47EJZVayVd9Yv6meNA4dOReO4MqTlPtFtFupnduRfkI=
  - secure: bANDhrwi1ItXZQiX4SWUaTxTM/PgXwuDUc037IhStFb/EsmYn3Z7KlM5AS3jyWb/I5JfS2LJOwAUXq7NTlNL/lcjEWux+w7mu21MlYnSaVSX/NhCR4n/2FzFI1RAWB9C37I8ec43BnXaPaKl32pxi9WbS4J68unN3AooCSDF5henG7VDH1sVYKceoDoKkyoulj0LTWIk+ZOk7gDE3NWSWx2oYCGSBl7zxICuv1oP4cgpuRsTHNbznb/AojQcg1Idmn0leeKWq/2aSWR9kTWqLJzSXA9byGZCLMHpAbhGiSMtT22pCD2mTgqkT+H10E4jYTccf7OEgUf5Tx/1ljMqd7hEs00mUDGb/TOQy31GUCxf6Ps8j6QmPGcAsCZ5fJNZiaWJP1+w9M7270iKmWoCaT2/rNgnuTWb0rH89veFHSoNc32OGbgPM3TZ3pWmhGbTnkewhJSFxaipp5qXsu6fOeM6Nrk9QhcsxjD5j62wgRT607W85GlmgaFI2ZrUKQPHkdNKHxF6JByLV0UQLS2WnKRUTmPAMPyQiq0ARYU4nPyQKJ05PtL7Mib11O5qLLAU2CT2AnszVBRwvw4a4NRqo+HVSrxEl1KKRWbY0twjF+3S0cPQ3aW21PuWVznKPC7b0bwOJxIVb0dA5UZS5mvxt8b4pFevzHji5NgZHV8Qr5I=
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
  BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, TAG=$TRAVIS_TAG, REPO=$REPO"
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker push $REPO:$TAG
